//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G7_DBFirstNew.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.RegisterSubjects = new HashSet<RegisterSubjects>();
        }
    
        public int StudentID { get; set; }

        //[Display(Name = "Name")]
        public string StudentName { get; set; }
        public int StudentAge { get; set; }
        public float StudentGrade { get; set; }
        public int StudentYearOfGraduation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterSubjects> RegisterSubjects { get; set; }
    }
}
