//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G7_DBFirstNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subjects()
        {
            this.RegisterSubjects = new HashSet<RegisterSubjects>();
        }
    
        public int SubjectID { get; set; }
        public string SubjectName { get; set; }
        public int SubjectNumOfStudent { get; set; }
        public int SubjectCurrentNumber { get; set; }
        public Nullable<int> RegisterSubject_RegSubID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterSubjects> RegisterSubjects { get; set; }
    }
}
