//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G7_DatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterSubject
    {
        public int RegSubID { get; set; }
        public Nullable<int> RegStudent_StudentID { get; set; }
        public Nullable<int> RegSubject_SubjectID { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
